name: color_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^1.0.4
  solid_lints: ^0.0.19
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
